In [2]:
from sklearn import svm  # S.V. Machine (Support Vector Machine)
import numpy as np

In [3]:
data = np.array([np.arange(0, 9), np.arange(0, 9)])
data = data.T
target = np.arange(0, 9)

print(data)
print(target)

[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]
 [7 7]
 [8 8]]
[0 1 2 3 4 5 6 7 8]


In [6]:
clf = svm.SVC()  # why no alpha?
clf.fit(data, target)

print(clf.predict([[100000, -100]]))

print(clf.support_)  # target
print(clf.support_vectors_)  # data
print(clf.n_support_)  # idk...


print(clf.decision_function(data))  # SVC uses 'decision_function' to predict result

clf.decision_function_shape = 'ovo'  # one-versus-one, so a lot of classifier will be created.
clf.fit(data, target)

print(clf.predict([[100000, -100]]))

print(clf.support_)  # target
print(clf.support_vectors_)  # data
print(clf.n_support_)  # idk...
print(clf.decision_function(data))

[8]
[0 1 2 3 4 5 6 7 8]
[[0. 0.]
 [1. 1.]
 [2. 2.]
 [3. 3.]
 [4. 4.]
 [5. 5.]
 [6. 6.]
 [7. 7.]
 [8. 8.]]
[1 1 1 1 1 1 1 1 1]
[[ 8.28711264  7.27738755  6.22754957  4.89575227  3.77883361  2.75986602
   1.75561312  0.75479322 -0.24532716]
 [ 7.26794192  8.28084929  6.26794192  5.18780102  3.8106116   2.75364434
   1.74178907  0.73900128 -0.2615419 ]
 [ 5.14201237  7.26006263  8.27589147  6.26006263  4.14201237  2.78305931
   1.74276026  0.73352894 -0.26868853]
 [ 2.77355247  5.10925112  7.25571678  8.27325427  6.25571678  4.10925112
   1.77355247  0.73857868 -0.26972126]
 [ 0.73755104  2.77129785  5.09864924  7.25448296  8.27251767  6.25448296
   4.09864924  1.77129785 -0.26244896]
 [-0.26972126  0.73857868  2.77355247  5.10925112  7.25571678  8.27325427
   6.25571678  4.10925112  1.77355247]
 [-0.26868853  0.73352894  1.74276026  2.78305931  5.14201237  7.26006263
   8.27589147  6.26006263  4.14201237]
 [-0.2615419   0.73900128  1.74178907  2.75364434  3.8106116   5.18780102
   7.2679

In [8]:
# in the other hand, LinearSVC:

lin_clf = svm.LinearSVC(max_iter=10000)
lin_clf.fit(data, target)
print(lin_clf.decision_function(data))
print(lin_clf.predict(data))

[[ 0.47059025 -0.16000746 -0.4078113  -0.54276044 -0.6545188  -0.76625613
  -0.8779943  -0.98971187 -1.17326172]
 [-0.70586823 -0.37333852 -0.50026725 -0.59397771 -0.67623819 -0.75849372
  -0.8407321  -0.92298947 -1.0647075 ]
 [-1.88232672 -0.58666958 -0.5927232  -0.64519497 -0.69795758 -0.75073131
  -0.8034699  -0.85626706 -0.95615327]
 [-3.0587852  -0.80000064 -0.68517916 -0.69641224 -0.71967697 -0.7429689
  -0.76620771 -0.78954466 -0.84759905]
 [-4.23524369 -1.0133317  -0.77763511 -0.74762951 -0.74139636 -0.73520649
  -0.72894551 -0.72282226 -0.73904482]
 [-5.41170217 -1.22666276 -0.87009106 -0.79884678 -0.76311575 -0.72744408
  -0.69168331 -0.65609985 -0.6304906 ]
 [-6.58816066 -1.43999382 -0.96254702 -0.85006404 -0.78483514 -0.71968167
  -0.65442111 -0.58937745 -0.52193637]
 [-7.76461914 -1.65332487 -1.05500297 -0.90128131 -0.80655454 -0.71191926
  -0.61715892 -0.52265505 -0.41338214]
 [-8.94107763 -1.86665593 -1.14745892 -0.95249858 -0.82827393 -0.70415684
  -0.57989672 -0.455932

In [9]:
# Regression

reg = svm.SVR()
reg.fit(data, target)
print(reg.predict([[100000, -100]]))

[4.]


In [11]:

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

s_svc = make_pipeline(StandardScaler(), svm.SVC())
s_lsvc = make_pipeline(StandardScaler(), svm.LinearSVC())
s_reg = make_pipeline(StandardScaler(), svm.SVR())

s_svc.fit(data, target)
s_lsvc.fit(data, target)
s_reg.fit(data, target)

print(clf.predict([[100000, -100]]))
print(lin_clf.predict([[100000, -100]]))
print(reg.predict([[100000, -100]]))

print(s_svc.predict([[100000, -100]]))
print(s_lsvc.predict([[100000, -100]]))
print(s_reg.predict([[100000, -100]]))


[8]
[8]
[4.]
[8]
[8]
[4.]


In [14]:
clf_linear = svm.SVC(kernel='linear')
clf_rbf = svm.SVC(kernel='rbf')
clf_poly = svm.SVC(kernel='poly')
clf_sig = svm.SVC(kernel='sigmoid')

clf_linear.fit(data, target)
clf_rbf.fit(data, target)
clf_poly.fit(data, target)
clf_sig.fit(data, target)

print(clf_linear.predict([[100000, -100]]))
print(clf_rbf.predict([[100000, -100]]))
print(clf_poly.predict([[100000, -100]]))
print(clf_sig.predict([[100000, -100]]))

[8]
[8]
[8]
[1]


In [13]:
def my_kernel(X, Y):
    return np.dot(X, Y.T)


clf_custom = svm.SVC(kernel=my_kernel)
clf_custom.fit(data, target)

print(clf_custom.predict([[100000, -100]]))

[8]


In [21]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

print("\n\nmake_classification:\n\n")
data_m, target_m = make_classification(n_samples=13, n_features=17)  # generate 13 by 17 matrix
train_data, test_data, train_target, test_target = train_test_split(data_m, target_m)

print(train_data)
print(train_target)
print(test_data)

clf_prec = svm.SVC(kernel='precomputed')

clf_prec.fit(np.dot(train_data, train_data.T), train_target)
print(clf_prec.predict(np.dot(test_data, train_data.T)))

print(test_target)




make_classification:


[[ 1.29842486 -0.5440734  -0.25823363  0.03163099  0.38663008 -1.02367946
   0.29778455  0.05013335 -2.09225972  0.36984473  0.73580967  0.07320197
  -0.12247396 -0.15905825  2.08147668  0.72884727 -0.53458376]
 [-1.61540494  0.44985508  1.96491422  0.64120242  0.77402126 -0.63062108
   0.58479063  0.16317018  1.48864583  0.73752174 -0.62203681 -0.91426506
   0.50157004  0.60880488 -1.14013847 -0.87202876 -0.67793618]
 [ 0.67767973 -0.14123158  0.16880906 -1.42899753  1.18967057  0.35882809
   0.79088892  0.12735498 -0.67794547 -0.49127257  0.18337596  0.24898889
  -0.62516584  0.95363817  0.174722    0.57793198  0.94928155]
 [ 0.30583111  0.10802072  0.5349883   0.42781452  1.47956052  1.09387359
   0.99058084 -1.02582347  1.61332683 -0.75762971 -0.07832695  1.32113783
   0.49694481 -0.5026572  -0.69964367 -2.51716749  0.28273404]
 [ 0.75974202 -0.41252654  0.42629847 -0.21899184  0.42424585  0.26488959
  -0.48404533 -0.82899065 -0.56400838  0.67213435  0.6157